version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    networks:
      - redis-network
    environment:
      - REDIS_ADDR=redis:6379

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - redis-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/provisioning/dashboards/config:/etc/grafana/provisioning/dashboards
      - ./config/grafana/provisioning/dashboards/dashboards:/var/lib/grafana/dashboards
    networks:
      - redis-network

networks:
  redis-network:
